export const BADGE_CATALOG = {
  first_quest: {
    id: 'first_quest',
    name: 'First Explorer',
    description: 'Complete your first quest',
    icon: '🗺️',
    criteria: { type: 'questCount', value: 1 },
  },
  level_3: {
    id: 'level_3',
    name: 'Bronze Path',
    description: 'Reach Level 3',
    icon: '🥉',
    criteria: { type: 'level', value: 3 },
  },
  level_6: {
    id: 'level_6',
    name: 'Silver Path',
    description: 'Reach Level 6',
    icon: '🥈',
    criteria: { type: 'level', value: 6 },
  },
  foodie: {
    id: 'foodie',
    name: 'Foodie Crawl',
    description: 'Complete 3 food-themed quests',
    icon: '🍜',
    criteria: { type: 'moodCount', mood: 'Foodie', value: 3 },
  },
  explorer: {
    id: 'explorer',
    name: 'Explorer',
    description: 'Complete 5 quests',
    icon: '🧭',
    criteria: { type: 'questCount', value: 5 },
  },
  adventurer: {
    id: 'adventurer',
    name: 'Adventurer',
    description: 'Visit 10 stops',
    icon: '🎒',
    criteria: { type: 'stopCount', value: 10 },
  },
  hardcore: {
    id: 'hardcore',
    name: 'Hardcore',
    description: 'Complete a Hard quest',
    icon: '💀',
    type: 'difficulty',
  },
  'streak-7': {
    id: 'streak-7',
    name: 'Flame Keeper',
    description: 'Maintain a 7-day streak',
    icon: '🔥',
    type: 'streak',
  },
  'explorer-5': {
    id: 'explorer-5',
    name: 'City Explorer',
    description: 'Complete quests in 5 cities',
    icon: '🌆',
    type: 'exploration',
  },
  'squad-player': {
    id: 'squad-player',
    name: 'Squad Player',
    description: 'Complete a group quest with 3+ members',
    icon: '👥',
    type: 'group',
  },
  'quest-10': {
    id: 'quest-10',
    name: 'Veteran',
    description: 'Complete 10 quests',
    icon: '🏅',
    type: 'milestone',
  },
};
